### ISSUE TITLE
Need to pass provider location in Order details for cascaded transactions

### ISSUE THREAD

**Issue by BLR-0118** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#11]
Reported by Grab:
Certain logistics providers need the provider location (seller address field) to create merchant record. While Order has provider.locations.id, the location details are only available within the same domain and not cross-domain. For cross-domain cascaded transaction, this information needs to be passed through.

**Comment by BLR-0118** [comment]
@Ajit-grab - please verify whether this is correct:
To Order, add:
- provider.name (i.e. retailer name)
- location.gps (i.e. retailer GPS) or location.address or both?
- anything else?

**Comment by Ajit-Grab** [comment]
Hi @BLR-0118 

Can You Please provide Sample Payload for this 

$ref: '#/components/schemas/Offer'


        item:


          $ref: '#/components/schemas/Item'


        ./ondc-payload_details:


          type: object


          description: payload details that will allow logistics provider to determine serviceability.<br>


                       For weight, enums for unit are:<br>


                       "Kilogram"<br>


                       "Gram"<br>


                       For dimensions, enums for length.unit, breadth.unit and height.unit are:<br>


                       "meter"<br>


                       "centimeter"<br>


          properties:


            weight:


              $ref: '#/components/schemas/Scalar'


            dimensions:


              $ref: '#/components/schemas/Dimensions'


        tags:


          $ref: '#/components/schemas/Tags'


    ItemQuantity:

**Comment by BLR-0118** [comment]
Added to ONDC Protocol Specs
