### ISSUE TITLE
Need to pass Order Item details in /confirm request for cascaded transaction

### ISSUE THREAD

**Issue by BLR-0118** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#12]
Reported by Grab:
How Grab will get Item Name, Item Unit Price, Item Wise Total and Item Weight in the confirm request payload? These are mandatory fields for order creation in Grab System. 
(Grab should be getting these fields in message.order.items object)

**Comment by Ajit-Grab** [comment]
Hi Team : Please share updates if any

**Comment by BLR-0118** [comment]
@Ajit-Grab will add this today

**Comment by BLR-0118** [comment]
@Ajit-Grab - what details do you need about the retail order to create the order in Grab?
Is this ok:
- package weight or dimensions or both
- retail order value (?)
- anything else?

**Comment by Ajit-Grab** [comment]
We need the below data for order creation.
•	Item Details with Item Name, Item Id, Unit Price, Quantity
•	Total Order Value
•	Order Payment Mode
•	If it is COD, then to collect amount
•	Package weight and dimension (Not mandatory)
•	Pickup Name and Address

**Comment by BLR-0118** [comment]
Added to ONDC Protocol Specs

**Comment by Ajit-Grab** [comment]
Hi , Please add the details to sample JSON as well
