### ISSUE TITLE
How does Retail BuyerApp indicate to Retail SellerApp that logistics would be handled by RetailBAP?

### ISSUE THREAD

**Issue by nirmay** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#18]
Currently, BAP can only indicate to BPP Retail that the choice of user it Pickup or Delivery. For 'delivery' type orders, BAP needs to inform BPP that it will identify the logistics provider by itself. There is no provision for SellerApp to know this in the spec today.

**Comment by BLR-0118** [comment]
Actually, the fulfillment.type is set by the seller. As defined in the spec:
 "Pickup" - Buyer picks up from store by themselves or through their logistics provider;
 "Delivery" - seller delivers to buyer
Isn't this clear?

**Comment by nirmay** [comment]
@BLR-0118 the case in question is different.
Let's say that the Buyer opts for Delivery. Now, both BuyerApp and SellerApp have the option to go out on the logistics network and identify a logistics provider (especially I believe right now there are some BuyerApps that are implementing Logistics cascaded transaction on their side). 
Now, when the BuyerApp that is meaning to go out to the logistics network, it is best if it indicates that to SellerApp, else its a dup search call on the Logistics network. 

reopening this for now, to see if this needs to be handled at protocol level.

**Comment by BLR-0118** [comment]
@nirmay for every item, fulfillment.type will be set, either to "Pickup" or "Delivery". The buyer will opt for delivery only if this is set to "Pickup" as in the case of "Delivery", the seller will deliver to buyer using their logistics provider on or off the network. Same applies if there is an Order where some of the items are for "Delivery" and others for "Pickup", in which case, the buyer will opt for delivery only for "Pickup" items. Hence, where's the question of duplicate search?

**Comment by BLR-0118** [comment]
Closing after agreement with @nirmay
