### ISSUE TITLE
Payment status needs additional state apart from "PAID" and "NOT-PAID"  as "PENDING" to tell the payment ACK is awaited.

### ISSUE THREAD

**Issue by VidyaGF** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#19]
In ecomm platforms , we will have the status as "Pending" till we obtain the confirmation status on the payment. And if  payment failed, we are asked to make the payment again. Similarly , in our case if we return "NOT-PAID" it would mean that payment is not done, while ,it only an ACK that is not been obtained. Can we have the additional state as "Pending" , so that it says the seller app that we are waiting for the payment confirmation ?

**Comment by VidyaGF** [comment]
@BLR-0118 - Please let us know if we can consider a new state will be added.

**Comment by BLR-0118** [comment]
@VidyaGF - not sure why you need an additional status in the Payment object itself? How does it help any of the counterparties if they know the status is "NOT-PAID" vs "Pending"?

**Comment by VidyaGF** [comment]
Once the payment is done and only ACK is not obtained by the Payment Gateway, then, neither "PAID" nor "NOT PAID" would be correct. Because payment is done but only status is awaited. How can I communicate this back to the seller?

**Comment by BLR-0118** [comment]
@VidyaGF - this is a temporary status, what value does it add by communicating back to seller? Is there some use-case that it facilitates?

**Comment by VidyaGF** [comment]
@BLR-0118 - In the payment object , as shown in the image , there are two status : One is transaction_status and other is status.
Now this is the usecase:
Buyer makes a payment to seller (say via payment gateway) for a prepaid payment type
The gateway responds with a processing state, so final status of transaction is not known .
In this case , what should be the transaction_status and status from the buyer to be returned back to the seller ?







![image](https://user-images.githubusercontent.com/67877265/162471234-a36a14f2-9487-46c0-a85b-b7925f07dd7d.png)

**Comment by BLR-0118** [comment]
transaction_status should actually be the transaction completion reference no as explained in the various scenarios in section 7 of the Payment & Settlement protocol doc

**Comment by VidyaGF** [comment]
Yes, in that case , how does the buyer communicate  to the seller that the transaction status is "Pending" and that the amount has been paid?

**Comment by BLR-0118** [comment]
From my understanding, this is a transient status which may not be of much use to the seller. Let's discuss this offline.

**Comment by VidyaGF** [comment]
sure

**Comment by BLR-0118** [comment]
added enum for "PENDING" to payment.status
