### ISSUE TITLE
Seller Serviceability 

### ISSUE THREAD

**Issue by AbhishekPassi** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#21]
How does the seller indicate area of servecibality for products sold by him ?
If he’s going to use on network logistics partner then serveciability will be checked as part of cascaded transaction flow.
However, if the seller would like to self fulfill or fulfill through off network logistics partners then his store or products from his store shouldn’t appear in the search by the buyer from the area which is not serviceable by his store

**Comment by BLR-0118** [comment]
@AbhishekPassi There are 2 ways to handle this now:
1. Buyer specifies the delivery location as part of the search intent. Seller can decide based on the delivery location whether to respond to search request;
2. Buyer does not specify the delivery location as part of the search intent. In this case, during Order initialization, when buyer provides delivery address, the seller can return a policy error for not serviceability.
