### ISSUE TITLE
For "Pickup" orders, how does BuyerApp communicate logistics status to SellerApp

### ISSUE THREAD

**Issue by nirmay** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#25]
If the fulfillment.type=Pickup, and Logistics transaction is complete, then Seller needs to be notified about the completion on tx. Since, BuyerApp is responsible for communciation with Logisitcs provider, it will have the status updated, but how should it now pass it to SellerApp?
Should this happen using /status call?
Is /status call allowed update state, or /update call with specific update_target?

**Comment by BLR-0118** [comment]
You should call /update with update_target="fulfillment"
