### ISSUE TITLE
Drive link not working

### ISSUE THREAD

**Issue by kausdaware** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#29]
In below power point presentation
https://github.com/Open-network-for-digital-commerce/ONDC-Protocol-Specs/blob/master/protocol-specifications/docs/draft/Tech%20Quickstart%20Guide.md,  this github link (https://github.com/dhiraj-nsdl/Beckn-API) is not working. (Slide 6)

**Comment by BLR-0118** [comment]
can you pls recheck, there's a different working link there

**Comment by kausdaware** [comment]
Check this  slide 6
https://docs.google.com/presentation/d/1OYVDmy58wB6jDvSJaxVfc5JwRG5rYMtmhqt7oG9Cp0Y/edit#slide=id.g10a40235bd9_0_53 



![github link](https://user-images.githubusercontent.com/25948405/167310008-2d239139-8e9f-4864-8ef3-64ffe58e1016.png)
