### ISSUE TITLE
Support for multiple fulfillments for multiple returns in given return window

### ISSUE THREAD

**Issue by JindalMohit** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#31]
Is buyer allowed to initiate multiple returns for a given order? If yes, then there will be multiple fulfillments in this case and order object does not support more than 1 fulfillment.

**Comment by BLR-0118** [comment]
As discussed with Beckn team, item-based fulfillment will be enabled in the protocol. Changes will be published in the spec and retail transaction contract shortly.
