### ISSUE TITLE
Need to have cancellation_reason_id at ONDC level

### ISSUE THREAD

**Issue by ravi-kumar-yadav** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#4]
We should have cancellation_reason_id defined at global (ONDC) level. As cancellation_reason_id acts on similar lines to that of status codes (few semantic bucket of reasons) which can be collated at ONDC level, this will also help in following:

- BAP  need not map the cancellation_reason_id for integration with each new BPP (retail/logistics)
- BAP can avoid an extra API call to fetch cancellation_reason_id (as caching may fail, if BPP modifies the cancellation_reason_id)

cancellation_reason_id can be thought similar to order_status_codes, which work great at ONDC level, independent from all BPP implementations.

**Comment by BLR-0118** [comment]
Added to Cancellation description
