### ISSUE TITLE
New order states for Logistics

### ISSUE THREAD

**Issue by ravi-kumar-yadav** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#5]
- shipped
Logistics partner will have reliable, faster update for shipped state

- rto_init
Once BAP/BPP(retail) has initiated cancellation, then Logistics BPP can mark the order in rto_init to notify the initiation of reverse journey for forward-order

- rto_delivered
Once order is delivered back to the source/origin (store) then Logistics BPP can mark the order in rto_delivered to notify the completion of reverse journey for forward-order

**Comment by nirmay** [comment]
Currently, logistics order only has "Active" and "Completed", there needs to be some mapping defined between retail order statuses (Created, Shipped, Delivered) with corresponding Logistics order states, since this status needs to be passed all the way to the buyer back in the cascaded flow.

**Comment by BLR-0118** [comment]
@ravi-kumar-yadav added to ONDC protocol specs
@nirmay - my understanding is that the logistics order state is generally passed all the way to the buyer and the retail order state is primarily for internal recording. If so, do we need this mapping?
