### ISSUE TITLE
[Logistics]

### ISSUE THREAD

**Issue by mherle** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#53]
Need a flag to indicate the order amount of the goods being carried. This is generally needed to ensure that the logistics for various reasons including (a) knowing the amount to collect (b) to accept/reject this based on declared goods value (ex: if you want to send an iPhone of 1L, and if the delivery is done via gig workers, you want to ensure its done only via right workers, as we cant take that risk. 

I suggest adding something like `"@ondc/org/order_value"` in the logistics order. 
For a cascaded transaction, the retail BPP should put the order value here
For a non-cascaded transaction, the logistics BAP can get this value from user and provide here.

**Comment by BLR-0118** [comment]
Check Order."@ondc/org/linked_order" which has declared_value. Hope this is ok.
@mherle

**Comment by BLR-0118** [comment]
@mherle is this ok?
