### ISSUE TITLE
[Quotation Price Breakup] Add enum value for discount for field "@ondc/org/title_type"

### ISSUE THREAD

**Issue by t-mabiswas** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#54]
In 1.0.13 schema, the enum values present for @ondc/org/title_type field of quotation.breakup are:
item, delivery, packing, tax, convenience charge

However, there is no enum supporting discounts price breakup type. An enum value should be introduced for this.

**Comment by BLR-0118** [comment]
added in 1.0.14
