### ISSUE TITLE
Provide retail order info like retail-order-id while confirming order with Logistics BPP

### ISSUE THREAD

**Issue by ravi-kumar-yadav** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#6]
We need to pass mandatory info like retail order id to Logistics Partner while confirming order. Currently we are just passing fulfilment info like source and destination address (and gps). But delivery agent need to share some order-id (unique identifier) to pick the order.

Currently as a hack we were using field: fulfillment.instructions, but we think it should be stored in a separate field.

```
"fulfillment": {
                "type": "home-delivery",
                "tracking": false,
                "start": {
                    "location": {
                        "id": "4847-OrderEasy-10002-3012_location",
                        "descriptor": {
                            "name": "Pooja Stores"
                        },
                        "gps": "13.08784,80.27847"
                    },
                    "time": {
                        "range": {
                            "start": "2021-12-30T07:09:30.000Z",
                            "end": "2021-12-30T07:10:30.000Z"
                        }
                    },
                    "instructions": {
                        "name": "pick up instructions",
                        "short_desc": "Provide the order id: <retail_order_id>"
                    },
                    "contact": {
                        "phone": "+919999999999",
                        "email": "info@poojastores.com"
                    }
                },
                "end": {
                    "location": {
                        "gps": "12.914028, 77.638698",
                        ...
```

This is the least info that needs to be passed (retail order id), like we aren't still passing items list to be checked before picking the package, so no check at the source yet

**Comment by BLR-0118** [comment]
I don't think this will work. Logistics providers have their own standard process which includes providing PCC (pickup confirmation code) to retailer who then tags it to the package. We've [defined](https://github.com/Open-network-for-digital-commerce/ONDC-Protocol-Specs/blob/master/protocol-specifications/docs/draft/Harmonizing%20statuses%20in%20cascaded%20retail%20%26%20logistics%20transaction.md) how this information should be communicated.
We're just trying to align the retailer with how logistics providers work today. Same process applies if buyer app invokes services of logistics provider on the network.
