### ISSUE TITLE
ONDC lack of "Getting Started" information for developers.

### ISSUE THREAD

**Issue by onchiptech** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#64]
I want to develop a buyer application and looking for some basic information.

Is there any documentation/guide for developing applications using ONDC protocol?
Where and how is the registry maintained? What is the url? How can a buyer/seller application be registered?
Could anyone point me to the documentation for getting started with the application development?

**Comment by BLR-0118** [comment]
The tech quickstart [guide](https://github.com/Open-network-for-digital-commerce/ONDC-Protocol-Specs/blob/master/protocol-specifications/docs/draft/Tech%20Quickstart%20Guide.md) is a good place to start
