### ISSUE TITLE
Need ENUM for fulfillment states

### ISSUE THREAD

**Issue by mherle** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#67]
Currently the Fulfillment object has a `state` property which is of type #/components/schemas/State which just has a `code` property. Need this to be an ONDC specified ENUM so that we can sync statuses. 

Here are the real world statuses that a hyperlocal order goes through:
- Agent is assigned
- Agent is on the way to pickup
- Agent reached pickup
- Agent has picked up the order and is enroute to drop
- Agent has reached the drop location
- Agent has delivered the order
- Order is cancelled (not sure if reasons have to be attributed here such as, Cancelled due to customer denied at door step, Cancelled due to location not found etc)

**Comment by BLR-0118** [comment]
Added in retail spec 1.0.17 and logistics spec 1.0.14
