### ISSUE TITLE
Define meaningful error codes for fulfillment

### ISSUE THREAD

**Issue by BLR-0118** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#69]
from Sreerag K (Paytm):
Currently the SellerNP returns the error code 30009 for the following cases and we display the error message "oops our seller partner is facing some issue. please try a different store"
1. Delivery partners not available
2. The delivery location is not serviceable by the logistics partner
3. The pickup location is not serviceable by the logistics partner
4. The delivery distance exceeds the maximum serviceable distance
The error message we display on PayTM needs to be different for these scenarios to direct the user to the next step and ensure a good user experience. Can we please have separate error codes for these cases so that we can display separate error messages and direct the user accordingly?

**Comment by BLR-0118** [comment]
@mahoriR @mherle @nirmay @ekanshKr @VidyaGF @siva-digiit - for your comments pls

**Comment by BLR-0118** [comment]
Updated error codes

**Comment by VidyaGF** [comment]
We had raised the issue ,so that we can send the right error message. Different error codes should solve the issue.
https://ondc-issue-logging-cohort1.atlassian.net/browse/COHORT1-233
