### ISSUE TITLE
Ready to Ship status

### ISSUE THREAD

**Issue by BLR-0118** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#8]
When the Retail Seller wants to inform Logistics Provider that the order is ready for pickup, which API will communicate take this proposed payload ?
Seller app needs to differentiate between an order that's ready for delivery vs an order that's being created that is not yet ready. This is actually a common use case, and could be handled either having 2 APIs (/create and /ship API) or having a flag in the order creation API called readyForDelivery and using the edit API for updating this later.
What flag can we use in the order create API /create to indicate whether this order is NOT yet ready for delivery ?
So, what we need is order is immediately ready for delivery - BAP will call /create and that's all order is created but after sometime will be marked as ready for shipping - BAP will call /create followed by /update
What we need is some guideline on how
(a) in /create  a seller can indicate the readytoship status - ready or not yet ready
(b) confirmation that this order property will be changed for the order via an /update call .
If I can get sample payloads for these 2, we can go ahead with this use case
This scenario is applicable in logistics-only txn also. There are cases where one might want to create the order in bulk and and only mark them ready for shipping after its made ready
Think of Bluedart customer service end point - they'll create an order with logistics to confirm price and availability and saying delivery is for tomorrow. But they themselves can handover the shipment only after its handed over to them by customer which might be tomorrow morning. an exec will check everything, confirm packaging is tight and scan it to say, its ready now.
As a short term solution, I can think of an informal agreement to have a specific note (via Tag mechanism) only to be used in this type of scenario, and by default one can assume its ready for delivery immediately

and logistics BAP can call update and update this Tag field from false to true to indicate to the logistics BPP. This can be set to false at the time of order's /confirm.
It can be handled by the retail seller to translate the retail order state to logistics order state.
For example:
a food delivery seller can call /update after 15mins of order placement (assuming 15min is the time taken),
a grocery delivery app can mark ready for delivery when, in their picker app, its marked as item picking and packing is complete.

**Comment by BLR-0118** [comment]
Use tag "./ondc-order_ready_to_ship" to communicate if order is ready to ship (documented in Fulfillment)

**Comment by nirmay** [comment]
Thanks for adding the new field to facilitate this important use case.
2 quick questions,
Which API would Logistics Buyer  use to send this tag /init or /confirm (the example above refers to create)
What are the enums for this tag? Ready / Not-Ready ?

**Comment by BLR-0118** [comment]
Since this status would typically be updated after confirmation of the order, you should use /update. This will have 2 values - no, yes as documented in the description for Fulfillment in the logistics spec

**Comment by nirmay** [comment]
So, if I understand this right, it will play out in 2 scenarios as per below,

1.
if the category/product-type demands a separate step to be marked readiness of the order by the seller, then /init (and not /confirm) should include the tag ./ondc-order_ready_to_ship = no, later when it is indeed ready, Logistics Buyer to trigger /update with ./ondc-order_ready_to_ship = yes.

2. If the category/product-type does not demand a separate step to marked readiness of the order by the seller, then /init should include the tag ./ondc-order_ready_to_ship = yes.

pls confirm.

**Comment by BLR-0118** [comment]
I think making the order ready to ship will always be a separate step that includes packaging, tagging the PCC and probably other steps. As such, where do you see point 2 being required?
