### ISSUE TITLE
Need to finalize the values for status in items array in /update and /on_update in new retail contract

### ISSUE THREAD

**Issue by siva-digiit** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#80]
![image](https://user-images.githubusercontent.com/102281172/185292589-dba85aed-0495-49dc-8076-98620446bdeb.png)
@BLR-0118

**Comment by akil4n** [comment]
@BLR-0118 - for the return items, how we are going to handle the status updates, Are we going to handle it with existing /status api

**Comment by BLR-0118** [comment]
enum added to API contract [here](https://docs.google.com/document/d/1osOKwHnpGrWoXAMONu8WXJ2AFOetyiRG7yYEO_gmRBU/edit) or [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit)
