### ISSUE TITLE
New cancellation codes to be created 

### ISSUE THREAD

**Issue by AayushSpaytm** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#82]
@BLR-0118 
As per the reference in the [doc](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit?usp=sharing) we are require two additional cases to be considered and codes be created for the following 
1. The buyer doesn't need the product anymore. 
2. The buyer wants to modify their details.

**Comment by BLR-0118** [comment]
1. Pls check cancellation code "012 Buyer does not want product any more" [here](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit). Isn't that the same one?
2. should we make it specific - like buyer wants to change order or change shipping address and can have separate codes for these. Any other details?

**Comment by BLR-0118** [comment]
@AayushSpaytm

**Comment by AayushSpaytm** [comment]
1. code 012 is for the case when logistics partner has cancelled stating buyer/buyer app doesn't want the product. The mentioned case is in the scenario buyer wants to cancel the product before shipment. Please let me know if this can be considered as a separate case here.
2.  For the time being we are considering all the changes that can be done in the buyer/shipping/logistics details under a single code. In the later we can attribute individual codes for specific changes in detail.

**Comment by BLR-0118** [comment]
1. I discussed with Ravi and removed "cancelled by" from the reason codes. Hence, 012 will suffice;
2. added as code "010"
updated doc is []([here](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit))

**Comment by BLR-0118** [comment]
@AayushSpaytm
