### ISSUE TITLE
Attribute required to inform the logistics provider that COD collection will be required by the Logistics Agent  during search request.

### ISSUE THREAD

**Issue by VidyaGF** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#9]
Which attribute should be used to inform the logistics provider while creating a logistics search request, that COD collection is not required?

Basis the order to be picked up is COD  or not, logistics seller may make a decision to respond to on_search. That would avoid cancellations later which is important in F &B

**Comment by nirmay** [comment]
Including CoD preference of Retail Buyer in the search request to Logistics network, will avoid negotiation between Logistics Buyer and Seller later in the flow.

A suggestion would be to include, `order.Payment.type = ON_FULFILLMENT` in the Search Intent. This need not be required parameter.

**Comment by VidyaGF** [comment]
But then it would tell about the logistics payment type, rather than the CoD preference of Retail Buyer ? Little confused here.

**Comment by BLR-0118** [comment]
I think we should delink when the payment is collected vs payment collection preference. One way to do this would be through a new attribute in the search intent. What do you think?

**Comment by VidyaGF** [comment]
I feel a new attribute in search intent will be better

**Comment by nirmay** [comment]
I did not realise that order.payment.type would represent the settlement between Logistics buyer and seller, for any instructions from Retail Seller, it would have to be a separate attribute.

**Comment by VidyaGF** [comment]
@BLR-0118 - Any  idea by when we can get this spec attribute?

**Comment by BLR-0118** [comment]
Will add Payment.collection_preference will have a single enum "CoD" for now

**Comment by VidyaGF** [comment]
ok , so Logistics Seller App can set values , CoD , prepaid and CoD , or prepaid only  , to let the Logistics Buyer know , that only such Retail orders it will accept for delivery.

**Comment by BLR-0118** [comment]
For now, there is 1 value - "CoD". This would normally be set as part of the search intent by the retailer, which is why this issue was filed.

**Comment by BLR-0118** [comment]
renamed payment.collection_preference to payment."./ondc-collection_preference"
